title: 'ARIA: heading ロール'
mdn_url: /ja/docs/Web/Accessibility/ARIA/Roles/heading_role
slug: Web/Accessibility/ARIA/Roles/heading_role
locale: ja
modified: 2019-03-18T16:22:47.301Z
mdn_contributors:
  - mdnwebdocs-bot
  - Wind1808
parent:
  slug: Web/Accessibility/ARIA/Roles/heading_role
  locale: en-US
  modified: 2019-06-12T03:59:56.555Z
