title: ROLE_DATE_EDITOR
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DATE_EDITOR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DATE_EDITOR
locale: en-US
modified: 2019-04-23T14:04:14.972Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
