title: ROLE_DIAL
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DIAL
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DIAL
locale: en-US
modified: 2019-04-23T14:04:21.624Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
