title: ROLE CAPTION
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CAPTION
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CAPTION
locale: ja
modified: 2019-04-25T13:06:16.938Z
mdn_contributors:
  - wbamberg
  - 5ara5treamer
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CAPTION
  locale: en-US
  modified: 2019-04-23T14:02:33.584Z
