title: ROLE_TERMINAL
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TERMINAL
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TERMINAL
locale: en-US
modified: 2019-04-23T14:05:54.922Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
