title: ROLE_APPLICATION
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_APPLICATION
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_APPLICATION
locale: en-US
modified: 2019-04-23T14:03:27.785Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
