title: ROLE LAYERED PANE
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LAYERED_PANE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LAYERED_PANE
locale: ja
modified: 2019-04-25T13:06:37.476Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Uemmra3
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LAYERED_PANE
  locale: en-US
  modified: 2019-04-23T14:02:54.312Z
